#!/bin/sh
# live-build Konfiguration für Cyjan IDS
# Aufruf: sudo lb config  (aus dem distro/-Verzeichnis)
set -ex

lb config noauto \
  --distribution      bookworm \
  --archive-areas     "main contrib non-free non-free-firmware" \
  --binary-images     iso-hybrid \
  --bootloaders       "syslinux,grub-efi" \
  --debian-installer  none \
  --memtest           none \
  --hostname          "cyjan-ids" \
  --username          "ids" \
  --password          "ids" \
  "${@}"
