#!/bin/sh
# live-build Konfiguration für Cyjan IDS
set -ex

lb config noauto \
  --distribution         bookworm \
  --archive-areas        "main contrib non-free non-free-firmware" \
  --binary-images        iso-hybrid \
  --bootloaders          "syslinux,grub-efi" \
  --debian-installer     none \
  --memtest              none \
  --bootappend-live      "boot=live components nomodeset fbcon=rotate:2 live-config.nocomponents=keyboard-configuration" \
  "${@}"
